# Import Library

In [1]:
# Basic Library
import time
import numpy as np
from tqdm import tqdm
import pandas as pd
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings("ignore", category=pd.errors.SettingWithCopyWarning)

# Custormized Package
from tools.cleansing import load_final_data

C:\Users\USER\python_code\sparta\project\final\tools\__init__.py:20: UserWarning:

사용법 안내: `load_data` 함수 사용 시, 인자는 다음 순서로 전달해야 합니다:

1. participant 테이블
2. position 테이블
3. match_info 테이블
4. objectives 테이블

정확한 인자 순서를 지켜 주세요.
예시) participant, position, match_info, objectives = load_data()

load_data 시, Dask 데이터프레임으로 추출하려면 to_pandas=False 인자를 추가해주세요

  warnings.warn(warning_message, UserWarning)

# Load Data

In [2]:
start_time = time.time()

pa = pd.read_csv('./data/final_data/participant.csv')
po = pd.read_csv('./data/final_data/position.csv')
mi = pd.read_csv('./data/final_data/match_info.csv')
ob = pd.read_csv('./data/final_data/objectives.csv')

end_time = time.time()  # 종료 시간 기록
elapsed_time = end_time - start_time  # 경과 시간 계산
print(f"총 소요 시간: {elapsed_time:.2f} 초")

총 소요 시간: 91.27 초

In [3]:
display(pa.head(3))
display(po.head(3))
display(mi.head(3))
display(ob.head(3))

,puuid,match_id,timestamp,currentGold,teamPosition,championName,goldPerSecond,jungleMinionsKilled,level,minionsKilled,participantId,timeEnemySpentControlled,totalGold,xp,totalDamageDone,totalDamageDoneToChampions,totalDamageTaken,abilityHaste,abilityPower,armor,armorPen,armorPenPercent,attackDamage,attackSpeed,bonusArmorPenPercent,bonusMagicPenPercent,ccReduction,cooldownReduction,health,healthMax,healthRegen,lifesteal,magicPen,magicPenPercent,magicResist,movementSpeed,omnivamp,physicalVamp,power,powerMax,powerRegen,spellVamp,kill,death,assist,involve_tower,involve_object,item_undo,item_transaction
0,---II-pqZEL_r8_NzYTZZJAD--uUlKHeOJ6Mp_A3ISi8i9...,KR_7108520522,0,500,JUNGLE,Nidalee,0,0,1,0,2,0,500,0,0,0,0,0,0,32,0,0,25,100,0,0,0,0,610,610,0,0,0,0,30,335,0,0,295,295,0,0,0,0,0,0,0,0,1
1,---II-pqZEL_r8_NzYTZZJAD--uUlKHeOJ6Mp_A3ISi8i9...,KR_7108520522,1,0,JUNGLE,Nidalee,0,0,1,0,2,0,500,0,301,301,0,0,9,32,0,0,58,110,0,0,0,0,620,620,12,0,0,0,30,335,0,0,240,295,12,0,0,0,0,0,0,0,0
2,---II-pqZEL_r8_NzYTZZJAD--uUlKHeOJ6Mp_A3ISi8i9...,KR_7108520522,2,111,JUNGLE,Nidalee,0,4,2,0,2,0,611,325,2964,301,679,0,9,35,0,0,60,142,0,0,0,0,491,708,19,0,0,0,31,431,0,0,186,328,64,0,0,0,0,0,0,0,0

,match_id,participantId,timestamp,position_x,position_y,lane,position_change
0,KR_6432746330,1,0,554,581,blue_zone,0.000000
1,KR_6432746330,1,1,7684,5189,jungle,8489.438380
2,KR_6432746330,1,2,6930,6742,mid,1726.361781

,puuid,tier,match_id,teamId,summonerName,summonerId,participantId,teamPosition,championName,mainRole,subRole,lane,kills,deaths,assists,summoner1Id,summoner2Id,totalMinionsKilled,neutralMinionsKilled,goldEarned,goldSpent,champExperience,item0,item1,item2,item3,item4,item5,item6,totalDamageDealt,totalDamageDealtToChampions,totalDamageTaken,damageDealtToBuildings,damageDealtToObjectives,damageDealtToTurrets,totalTimeSpentDead,visionScore,win,timePlayed,abilityUses,skillshotsDodged,skillshotsHit,enemyChampionImmobilizations,laneMinionsFirst10Minutes,controlWardsPlaced,wardTakedowns,effectiveHealAndShielding,dragonTakedowns,baronTakedowns,alliedJungleMonsterKills,enemyJungleMonsterKills,epicMonsterKillsNearEnemyJungler,getTakedownsInAllLanesEarlyJungleAsLaner,jungleCsBefore10Minutes,junglerTakedownsNearDamagedEpicMonster,kda,killsOnOtherLanesEarlyJungleAsLaner,takedownsBeforeJungleMinionSpawn,junglerKillsEarlyJungle,killsOnLanersEarlyJungleAsJungler
0,lZMvyyMT3ANaDFo_076zV17apcUO3hbjW9i6Iy2tUws1Hx...,3.0,KR_6432746330,100,돼지 주호,qhvyRiRwnByLziJhByfr0EvP0bcr67gyN2TfBYjnVQbK8Cmq,1,MIDDLE,Ekko,Assassin,Mage,MIDDLE,4,2,1,12,4,150,12,9352,8225,11566,3100,3152,3020,0,0,1082,3340,114798,13306,14914,4288,4288,4288,60,18,True,1501,147,19,35,6,61,1,0,0.000000,0,0,6,6,0,0.0,0.0,0,2.500000,0.0,0,NaN,NaN
1,tlmcyTaUgTosdPNrdC1vDDBaySTcVAiE_h8jwSdiBKZi0R...,3.0,KR_6432746330,100,남양주 차은우,0N48cPAvkf-4CHm6LMWGQt5dl_DvFFiGtxdWucSzmbnNqi...,2,BOTTOM,Caitlyn,Marksman,NaN,BOTTOM,7,3,12,4,7,187,4,11972,11850,11546,1055,6671,3094,3006,3156,1038,3363,122131,15822,12697,5749,6097,5749,66,20,True,1501,101,10,22,3,90,2,3,418.457275,1,0,0,1,0,0.0,0.0,0,6.333333,0.0,0,NaN,NaN
2,rGe_LFLivjZOXsm_V8a7r7204ux_Ex9OXjzjvF-yKTB2l_...,3.0,KR_6432746330,100,롯뎨마트,D0Jc_rjxymyJPYQ9TqrM-jVqOk_bM_BtWYzStROBd6Qzm0s,3,UTILITY,Xerath,Mage,Support,BOTTOM,9,6,9,4,14,20,4,9904,9710,8737,4628,3853,2421,6655,3020,1029,3364,53243,23962,14558,1638,1638,1638,144,57,True,1501,192,8,15,14,3,3,3,0.000000,0,0,0,0,0,0.0,0.0,0,3.000000,0.0,0,NaN,NaN

,match_id,teamId,baron_kills,champion_kills,dragon_kills,inhibitor_kills,riftHerald_kills,tower_kills,horde_kills
0,KR_6432746330,100,0,29,2,2,2,10,NaN
1,KR_6432746330,200,0,18,0,0,0,2,NaN
2,KR_6434689074,100,0,50,4,2,0,11,NaN

# Variable Preset

In [4]:
mi['timePlayed'] = mi['timePlayed'].apply(lambda x: round(x/60,1))
mi.head(3)

,puuid,tier,match_id,teamId,summonerName,summonerId,participantId,teamPosition,championName,mainRole,subRole,lane,kills,deaths,assists,summoner1Id,summoner2Id,totalMinionsKilled,neutralMinionsKilled,goldEarned,goldSpent,champExperience,item0,item1,item2,item3,item4,item5,item6,totalDamageDealt,totalDamageDealtToChampions,totalDamageTaken,damageDealtToBuildings,damageDealtToObjectives,damageDealtToTurrets,totalTimeSpentDead,visionScore,win,timePlayed,abilityUses,skillshotsDodged,skillshotsHit,enemyChampionImmobilizations,laneMinionsFirst10Minutes,controlWardsPlaced,wardTakedowns,effectiveHealAndShielding,dragonTakedowns,baronTakedowns,alliedJungleMonsterKills,enemyJungleMonsterKills,epicMonsterKillsNearEnemyJungler,getTakedownsInAllLanesEarlyJungleAsLaner,jungleCsBefore10Minutes,junglerTakedownsNearDamagedEpicMonster,kda,killsOnOtherLanesEarlyJungleAsLaner,takedownsBeforeJungleMinionSpawn,junglerKillsEarlyJungle,killsOnLanersEarlyJungleAsJungler
0,lZMvyyMT3ANaDFo_076zV17apcUO3hbjW9i6Iy2tUws1Hx...,3.0,KR_6432746330,100,돼지 주호,qhvyRiRwnByLziJhByfr0EvP0bcr67gyN2TfBYjnVQbK8Cmq,1,MIDDLE,Ekko,Assassin,Mage,MIDDLE,4,2,1,12,4,150,12,9352,8225,11566,3100,3152,3020,0,0,1082,3340,114798,13306,14914,4288,4288,4288,60,18,True,25.0,147,19,35,6,61,1,0,0.000000,0,0,6,6,0,0.0,0.0,0,2.500000,0.0,0,NaN,NaN
1,tlmcyTaUgTosdPNrdC1vDDBaySTcVAiE_h8jwSdiBKZi0R...,3.0,KR_6432746330,100,남양주 차은우,0N48cPAvkf-4CHm6LMWGQt5dl_DvFFiGtxdWucSzmbnNqi...,2,BOTTOM,Caitlyn,Marksman,NaN,BOTTOM,7,3,12,4,7,187,4,11972,11850,11546,1055,6671,3094,3006,3156,1038,3363,122131,15822,12697,5749,6097,5749,66,20,True,25.0,101,10,22,3,90,2,3,418.457275,1,0,0,1,0,0.0,0.0,0,6.333333,0.0,0,NaN,NaN
2,rGe_LFLivjZOXsm_V8a7r7204ux_Ex9OXjzjvF-yKTB2l_...,3.0,KR_6432746330,100,롯뎨마트,D0Jc_rjxymyJPYQ9TqrM-jVqOk_bM_BtWYzStROBd6Qzm0s,3,UTILITY,Xerath,Mage,Support,BOTTOM,9,6,9,4,14,20,4,9904,9710,8737,4628,3853,2421,6655,3020,1029,3364,53243,23962,14558,1638,1638,1638,144,57,True,25.0,192,8,15,14,3,3,3,0.000000,0,0,0,0,0,0.0,0.0,0,3.000000,0.0,0,NaN,NaN

In [5]:
ob = ob.dropna()

ob['monster_kills'] = ob[['baron_kills', 
                          'dragon_kills', 
                          'riftHerald_kills',
                          'horde_kills']].sum(axis=1)
ob['building_kills'] = ob[['inhibitor_kills', 
                           'tower_kills']].sum(axis=1)
ob['objective_kills'] = ob[['monster_kills', 
                           'building_kills']].sum(axis=1)

ob.head(3)

,match_id,teamId,baron_kills,champion_kills,dragon_kills,inhibitor_kills,riftHerald_kills,tower_kills,horde_kills,monster_kills,building_kills,objective_kills
8346,KR_6745793645,100,1,32,2,1,1,9,0.0,4.0,10,14.0
8347,KR_6745793645,200,0,21,1,0,0,2,0.0,1.0,2,3.0
8348,KR_6745829704,100,0,0,0,0,0,0,0.0,0.0,0,0.0

In [6]:
# 킬관여율
mi = pd.merge(mi, ob[['match_id','teamId','champion_kills']],
              on = ['match_id','teamId'],
              how = 'inner')

mi['kill_involve_ratio'] = round((mi['kills'] + mi['assists']) / mi['champion_kills'],3)
mi['kill_involve_ratio'] = mi['kill_involve_ratio'].fillna(0)
mi = mi.drop(['champion_kills'],axis=1)

# CS
mi['cs'] = mi['totalMinionsKilled'] + mi['neutralMinionsKilled']

# item_duplication 컬럼 추가
def calculate_max_duplication(row):
    item_counts = row[row != 0].value_counts()
    if item_counts.empty:
        return 0
    max_duplication = item_counts.max()
    return max_duplication

# item0부터 item5까지의 열만 선택하여 중복 횟수 계산
mi['item_duplication'] = mi[['item0', 'item1', 'item2', 'item3', 'item4', 'item5']].apply(calculate_max_duplication, axis=1)

mi.head(3)

,puuid,tier,match_id,teamId,summonerName,summonerId,participantId,teamPosition,championName,mainRole,subRole,lane,kills,deaths,assists,summoner1Id,summoner2Id,totalMinionsKilled,neutralMinionsKilled,goldEarned,goldSpent,champExperience,item0,item1,item2,item3,item4,item5,item6,totalDamageDealt,totalDamageDealtToChampions,totalDamageTaken,damageDealtToBuildings,damageDealtToObjectives,damageDealtToTurrets,totalTimeSpentDead,visionScore,win,timePlayed,abilityUses,skillshotsDodged,skillshotsHit,enemyChampionImmobilizations,laneMinionsFirst10Minutes,controlWardsPlaced,wardTakedowns,effectiveHealAndShielding,dragonTakedowns,baronTakedowns,alliedJungleMonsterKills,enemyJungleMonsterKills,epicMonsterKillsNearEnemyJungler,getTakedownsInAllLanesEarlyJungleAsLaner,jungleCsBefore10Minutes,junglerTakedownsNearDamagedEpicMonster,kda,killsOnOtherLanesEarlyJungleAsLaner,takedownsBeforeJungleMinionSpawn,junglerKillsEarlyJungle,killsOnLanersEarlyJungleAsJungler,kill_involve_ratio,cs,item_duplication
0,wlWE8MqLSzyc9LVb-4RLWG3xmK46F8pknz0Hy17HPlHZFG...,2.0,KR_6745793645,100,normal player,CaMFJUT6hCaou7CROG0Jy3-dl5grYWMU3KEyp7kRUEyIaQ,1,TOP,Gangplank,Fighter,NaN,TOP,4,7,9,14,4,153,12,11667,10650,13645,2031,3158,6676,3508,6675,0,3340,148791,16296,17662,5629,5629,5629,115,18,True,26.1,321,7,13,0,46,0,3,0.000000,0,0,12,0,0,0.0,0.0,1,1.857143,0.0,0,NaN,NaN,0.406,165,1
1,IDEtGY05gR-JaOznTMdbqn0Hgz3FzzgH2qETiItesa2DkG...,2.0,KR_6745793645,100,매널스메잇킷메엔,GJAMgEEgi58g0pW6hH62hkKwR_DZMys-ID7M_2L5KtQYqV...,2,JUNGLE,Viego,Fighter,Assassin,JUNGLE,12,7,5,4,11,41,113,13098,11483,12370,3071,6672,3078,1036,3111,0,3364,188527,19419,29581,2447,39165,2447,200,26,True,26.1,306,6,17,23,4,4,6,0.000000,2,1,48,3,0,NaN,48.0,0,2.428571,NaN,0,0.0,3.0,0.531,154,1
2,kT8IynjB428UgIrxayeTDsTlS6aPaYIMBDeB0590Zp8Ih9...,2.0,KR_6745793645,100,잠실제일검,v94l6IjPEvaZrItU5JM0Ffd3m7I8dSB-klvLq2JDlKMx6X...,3,MIDDLE,Orianna,Mage,Support,MIDDLE,6,3,10,12,4,136,0,10351,8925,13209,2421,0,2055,6655,3040,3020,3363,92431,15053,12556,3524,3524,3524,63,17,True,26.1,219,6,43,17,60,2,1,548.479736,0,0,0,0,0,0.0,0.0,0,5.333333,0.0,0,NaN,NaN,0.500,136,1

In [7]:
# 관여
involve = pa[['match_id','participantId','puuid',
              'timestamp','involve_tower','involve_object']]

# 순거래량
pa['transaction_margin'] = pa['item_transaction'] - pa['item_undo']
transaction = pa[['match_id', 'participantId','puuid', 
                  'timestamp', 'transaction_margin']]
transaction.loc[(transaction['timestamp'] == 0) & (transaction['transaction_margin'] < 0), 'transaction_margin'] = 1

# 스탯
pa['attack_stat'] = pa['attackDamage'] + pa['abilityPower']
pa['defense_stat'] = pa['armor'] + pa['magicResist']
pa['max_health'] = pa['healthMax']

stat = pa[['match_id', 'participantId','puuid', 'timestamp', 
           'attack_stat', 'attackSpeed', 'defense_stat', 'max_health']]

# 합치기
result = pd.merge(involve,transaction,on=['match_id','participantId','puuid','timestamp'])
result = pd.merge(result,stat,on=['match_id','participantId','puuid','timestamp'])
result = pd.merge(result,
                  po[['match_id','participantId','timestamp','position_change','lane']],
                  on=['match_id','participantId','timestamp'])
result = pd.merge(result, 
                  pa[['match_id','participantId','timestamp','death','totalGold','level']],
                  on=['match_id','participantId','timestamp'])

result

,match_id,participantId,puuid,timestamp,involve_tower,involve_object,transaction_margin,attack_stat,attackSpeed,defense_stat,max_health,position_change,lane,death,totalGold,level
0,KR_7108520522,2,---II-pqZEL_r8_NzYTZZJAD--uUlKHeOJ6Mp_A3ISi8i9...,0,0,0,1,25,100,62,610,0.000000,blue_zone,0,500,1
1,KR_7108520522,2,---II-pqZEL_r8_NzYTZZJAD--uUlKHeOJ6Mp_A3ISi8i9...,1,0,0,0,67,110,62,620,6956.592341,mid,0,500,1
2,KR_7108520522,2,---II-pqZEL_r8_NzYTZZJAD--uUlKHeOJ6Mp_A3ISi8i9...,2,0,0,0,69,142,66,708,4512.361909,jungle,0,611,2
3,KR_7108520522,2,---II-pqZEL_r8_NzYTZZJAD--uUlKHeOJ6Mp_A3ISi8i9...,3,0,0,0,72,114,71,800,6076.655741,jungle,0,967,3
4,KR_7108520522,2,---II-pqZEL_r8_NzYTZZJAD--uUlKHeOJ6Mp_A3ISi8i9...,4,0,0,0,90,117,76,896,2987.337443,jungle,0,1395,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20299595,KR_7143943970,9,zzztaI3OFGA0YQ4LxztCphd_MK9B3BnZgmOvG9oGBvyZ1d...,12,0,0,0,157,168,92,1365,844.704090,bottom,0,5173,8
20299596,KR_7143943970,9,zzztaI3OFGA0YQ4LxztCphd_MK9B3BnZgmOvG9oGBvyZ1d...,13,1,0,3,160,173,97,1465,2376.428413,bottom,0,6034,9
20299597,KR_7143943970,9,zzztaI3OFGA0YQ4LxztCphd_MK9B3BnZgmOvG9oGBvyZ1d...,14,1,0,0,160,209,97,1465,7210.928720,mid,0,6794,9
20299598,KR_7143943970,9,zzztaI3OFGA0YQ4LxztCphd_MK9B3BnZgmOvG9oGBvyZ1d...,15,0,0,1,160,209,97,1465,774.648307,mid,0,7320,9
20299599,KR_7143943970,9,zzztaI3OFGA0YQ4LxztCphd_MK9B3BnZgmOvG9oGBvyZ1d...,16,0,0,0,162,211,104,1569,2929.968259,mid,0,7804,10

# SQL Normailze

In [8]:
match_tier = mi[['match_id','tier', 'timePlayed']].drop_duplicates(subset=['match_id']).reset_index(drop=True)
team_result = pd.merge(mi[['match_id', 'teamId', 'win']],
                      ob[['match_id', 'teamId', 'champion_kills', 'monster_kills', 'building_kills']],
                      on=['match_id', 'teamId']).drop_duplicates(subset=['match_id', 'teamId']).reset_index(drop=True)
participant_preset = mi[['match_id','teamId','puuid','teamPosition','championName',
                         'summoner1Id', 'summoner2Id']]
participant_minute = result.drop(['participantId'],axis=1)
participant_result = mi[['match_id', 'puuid', 'kill_involve_ratio', 'deaths','cs', 'goldEarned',
                         'goldSpent','champExperience','item_duplication','totalDamageDealtToChampions',
                         'damageDealtToObjectives','totalTimeSpentDead','visionScore',
                         'abilityUses','skillshotsDodged','laneMinionsFirst10Minutes',
                         'alliedJungleMonsterKills','enemyJungleMonsterKills', 'kda',
                         'jungleCsBefore10Minutes','takedownsBeforeJungleMinionSpawn']]
champion = pd.read_csv('./data/champion.csv')


print(f'match_tier : {len(match_tier.columns)} columns x \
{len(match_tier)} rows')
display(match_tier.head(3))
print(f'team_result : {len(team_result.columns)} columns x \
{len(team_result)} rows')
display(team_result.head(3))
print(f'participant_preset : {len(participant_preset.columns)} columns x \
{len(participant_preset)} rows')
display(participant_preset.head(3))
print(f'participant_minute : {len(participant_minute.columns)} columns x \
{len(participant_minute)} rows')
display(participant_minute.head(3))
print(f'participant_result : {len(participant_result.columns)} columns x \
{len(participant_result)} rows')
display(participant_result.head(3))
print(f'champion : {len(champion.columns)} columns x \
{len(champion)} rows')
display(champion.head(3))

match_tier : 3 columns x 71571 rows

        match_id  tier  timePlayed
0  KR_6745793645   2.0        26.1
1  KR_6745829704   2.0         1.8
2  KR_6745854072   2.0        31.5

team_result : 6 columns x 143142 rows

        match_id  teamId    win  champion_kills  monster_kills  building_kills
0  KR_6745793645     100   True              32            4.0              10
1  KR_6745793645     200  False              21            1.0               2
2  KR_6745829704     100   True               0            0.0               0

participant_preset : 7 columns x 713355 rows

,match_id,teamId,puuid,teamPosition,championName,summoner1Id,summoner2Id
0,KR_6745793645,100,wlWE8MqLSzyc9LVb-4RLWG3xmK46F8pknz0Hy17HPlHZFG...,TOP,Gangplank,14,4
1,KR_6745793645,100,IDEtGY05gR-JaOznTMdbqn0Hgz3FzzgH2qETiItesa2DkG...,JUNGLE,Viego,4,11
2,KR_6745793645,100,kT8IynjB428UgIrxayeTDsTlS6aPaYIMBDeB0590Zp8Ih9...,MIDDLE,Orianna,12,4

participant_minute : 15 columns x 20299600 rows

,match_id,puuid,timestamp,involve_tower,involve_object,transaction_margin,attack_stat,attackSpeed,defense_stat,max_health,position_change,lane,death,totalGold,level
0,KR_7108520522,---II-pqZEL_r8_NzYTZZJAD--uUlKHeOJ6Mp_A3ISi8i9...,0,0,0,1,25,100,62,610,0.000000,blue_zone,0,500,1
1,KR_7108520522,---II-pqZEL_r8_NzYTZZJAD--uUlKHeOJ6Mp_A3ISi8i9...,1,0,0,0,67,110,62,620,6956.592341,mid,0,500,1
2,KR_7108520522,---II-pqZEL_r8_NzYTZZJAD--uUlKHeOJ6Mp_A3ISi8i9...,2,0,0,0,69,142,66,708,4512.361909,jungle,0,611,2

participant_result : 21 columns x 713355 rows

,match_id,puuid,kill_involve_ratio,deaths,cs,goldEarned,goldSpent,champExperience,item_duplication,totalDamageDealtToChampions,damageDealtToObjectives,totalTimeSpentDead,visionScore,abilityUses,skillshotsDodged,laneMinionsFirst10Minutes,alliedJungleMonsterKills,enemyJungleMonsterKills,kda,jungleCsBefore10Minutes,takedownsBeforeJungleMinionSpawn
0,KR_6745793645,wlWE8MqLSzyc9LVb-4RLWG3xmK46F8pknz0Hy17HPlHZFG...,0.406,7,165,11667,10650,13645,1,16296,5629,115,18,321,7,46,12,0,1.857143,0.0,0
1,KR_6745793645,IDEtGY05gR-JaOznTMdbqn0Hgz3FzzgH2qETiItesa2DkG...,0.531,7,154,13098,11483,12370,1,19419,39165,200,26,306,6,4,48,3,2.428571,48.0,0
2,KR_6745793645,kT8IynjB428UgIrxayeTDsTlS6aPaYIMBDeB0590Zp8Ih9...,0.500,3,136,10351,8925,13209,1,15053,3524,63,17,219,6,60,0,0,5.333333,0.0,0

champion : 3 columns x 168 rows

  championName  mainRole   subRole
0       Aatrox   Fighter       NaN
1         Ahri      Mage  Assassin
2        Akali  Assassin       NaN

In [9]:
match_tier.to_csv('./data/after_norm/match_tier.csv', index=False)
team_result.to_csv('./data/after_norm/team_result.csv', index=False)
participant_preset.to_csv('./data/after_norm/participant_preset.csv', index=False)
participant_minute.to_csv('./data/after_norm/participant_minute.csv', index=False)
participant_result.to_csv('./data/after_norm/participant_result.csv', index=False)
champion.to_csv('./data/after_norm/champion.csv', index=False)

# Make Final Data

In [10]:
df = load_final_data()
display(df)
df.to_csv('./data/final_df.csv',index=False)

데이터 불러오는 중..
데이터 병합 중..

100%|██████████████████████████████████████████████████████████████████████████████████| 11/11 [01:12<00:00,  6.63s/it]

,match_id,tier,timePlayed,teamId,win,champion_kills,monster_kills,building_kills,puuid,teamPosition,championName,takedownsBeforeJungleMinionSpawn,mainRole,summoner1Id,summoner2Id,kill_involve_ratio,deaths,cs,goldEarned,goldSpent,champExperience,item_duplication,totalDamageDealtToChampions,damageDealtToObjectives,totalTimeSpentDead,visionScore,abilityUses,skillshotsDodged,laneMinionsFirst10Minutes,alliedJungleMonsterKills,enemyJungleMonsterKills,kda,jungleCsBefore10Minutes,subRole,tower_involve_ratio,object_involve_ratio,average_transaction_margin_per_10min,delta_attack_stat,delta_attackSpeed,delta_defense_stat,delta_max_health,no_moving_minute,deathBefore10Minutes,goldBefore10Minutes,level10Minutes
0,KR_6745793645,2.0,26.1,100,True,32,4.0,10,wlWE8MqLSzyc9LVb-4RLWG3xmK46F8pknz0Hy17HPlHZFG...,TOP,Gangplank,0,Fighter,Ignite,Flash,0.406,7,165,11667,10650,13645,1,16296,5629,115,18,321,7,46,12,0,1.857143,0.0,-,30.0,0.0,6.54,11.3,1.6,3.4,65.0,0.0,4,3539.0,8.0
1,KR_6745793645,2.0,26.1,100,True,32,4.0,10,IDEtGY05gR-JaOznTMdbqn0Hgz3FzzgH2qETiItesa2DkG...,JUNGLE,Viego,0,Fighter,Flash,Smite,0.531,7,154,13098,11483,12370,1,19419,39165,200,26,306,6,4,48,3,2.428571,48.0,Assassin,10.0,100.0,6.92,10.7,4.7,4.5,77.6,0.0,1,4011.0,7.0
2,KR_6745793645,2.0,26.1,100,True,32,4.0,10,kT8IynjB428UgIrxayeTDsTlS6aPaYIMBDeB0590Zp8Ih9...,MIDDLE,Orianna,0,Mage,Teleport,Flash,0.500,3,136,10351,8925,13209,1,15053,3524,63,17,219,6,60,0,0,5.333333,0.0,Support,30.0,0.0,8.08,10.0,2.2,3.1,63.8,0.0,2,3043.0,8.0
3,KR_6745793645,2.0,26.1,100,True,32,4.0,10,BLETPcJypWgvezu1sXgu6D3y4PHE9J0Im1EmoG237pci_N...,BOTTOM,Kaisa,0,Marksman,Heal,Flash,0.500,1,243,14217,11625,14211,1,20733,18981,26,22,139,5,75,0,1,16.000000,0.0,Mage,40.0,0.0,6.92,10.0,6.5,3.0,59.2,0.0,0,3956.0,7.0
4,KR_6745793645,2.0,26.1,100,True,32,4.0,10,TFxBalyWaL40iK1WrLx930UIkiKn2cdQ816MHWeup0AUAv...,UTILITY,Leona,0,Tank,Ignite,Flash,0.562,3,31,7860,6600,10086,1,7171,754,55,55,117,12,14,0,0,6.000000,0.0,Support,0.0,0.0,5.77,4.8,1.2,7.7,85.8,0.0,1,2451.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
713290,KR_7153806610,2.0,1.9,200,True,0,0.0,0,9ftft0MiiHrGp6coIEdv_xNCWYGSEPnVVSD0MvfQt2FYmT...,JUNGLE,Warwick,0,Fighter,Flash,Smite,0.000,0,4,601,500,325,1,0,0,0,0,3,0,0,1,0,0.000000,4.0,Tank,0.0,0.0,10.00,45.0,13.0,0.0,10.0,0.0,0,NaN,NaN
713291,KR_7153806610,2.0,1.9,200,True,0,0.0,0,Jwho46enAHraELcouZ-F2BWth4UWXNbchZeKWOSKfJYJLu...,TOP,Aatrox,0,Fighter,Teleport,Flash,0.000,0,0,511,500,0,1,72,0,0,0,5,0,0,0,0,0.000000,0.0,-,0.0,0.0,10.00,45.0,0.0,0.0,120.0,0.0,0,NaN,NaN
713292,KR_7153806610,2.0,1.9,200,True,0,0.0,0,-MS6cCD97HsowVdti83vtJVOOwkPRQlzHRKkTejSS0XK-D...,MIDDLE,Sylas,0,Mage,Ignite,Flash,0.000,0,0,511,500,123,1,506,0,0,0,5,1,0,0,0,0.000000,0.0,Assassin,0.0,0.0,10.00,72.0,0.0,0.0,100.0,0.0,0,NaN,NaN
713293,KR_7153806610,2.0,1.9,200,True,0,0.0,0,QHAjCYlMqvB72AqJjNg1-JnUzkE2eJIVPK4A2qqJ-ZLEYH...,UTILITY,Karma,0,Mage,Ignite,Flash,0.000,0,0,512,500,0,1,0,0,0,0,3,0,0,0,0,0.000000,0.0,Support,0.0,0.0,10.00,44.0,0.0,0.0,40.0,0.0,0,NaN,NaN
713294,KR_7153806610,2.0,1.9,200,True,0,0.0,0,1iPlL-OCbURe8KMBkNo34tBNStT1snP9r2C3BKkhp1bosn...,BOTTOM,Ezreal,0,Marksman,Barrier,Flash,0.000,0,0,511,500,0,1,0,0,0,0,4,0,0,0,0,0.000000,0.0,Mage,0.0,0.0,0.00,42.0,10.0,0.0,65.0,0.0,0,NaN,NaN

소현 튜터님이 어제 호출하셔서 얘기나눴던거
중간발표
1. 데이터 소개는 Raw데이터 다 보여줄 필요없이 어느 정도 정제된 데이터 (sql 정규화한 데이터 보여드렸을 때 괜찮을거 같다고 하셨음) + ERD (스키마 다이어그램) 으로 하면 될 것 같음
2. EDA는 
	i. 기초통계량(기술통계 및 상관관계)
	ii. 트롤을 잡기 위해서 정상적인 매치만 추려내기 위해 어떤 작업 했는지
	iii. 사전에 정의한 트롤에 대한 지표 관련 EDA 몇개
정도로 진행하면 어떻겠냐고 여쭤봤을 때 OK.
3. 결론 부분에선 향후 계획(모델링) 어떻게해서 트롤 어떻게 잡고 어떤 대시보드 만들지 보여주면 될듯

최종 발표
모델링 > 
비지도 학습 기반 but, 정상/비정상 비율 많이 불균형할때 99:1 > 정상인 데이터만 모델에 학습 > 검증 비정상 > 인코딩-디코딩 노이즈 생기기 때문에 얘는 비정상!
1. ML 모델 2개 정도 돌려서 만장일치로 정상 or 만장일치로 비정상
2. 비지도학습 기반 ML 모델 같은 경우에는 <파라미터 조정> 엄청 빡셀거다. 실제로 분석가 정돈면 DL은 사용안해도 될거 같고 > 2개이상의 모델을 써서 보팅 모델같은 (SVDD, ISF, OCSVM) -> 보팅 모델 만든거까지 

클러스터링 진행했을 때 > 얘에 대해서 실루엣 계수 괜찮게 나오고 실제로 만들어진 군집에 대한 해석이 잘된다

(태블로 빡셀거 같으면 스트림릿)